USE [master]
GO
/****** Object:  Database [Project1Todo]    Script Date: 1/21/2017 10:15:23 AM ******/
IF EXISTS(SELECT name FROM sys.databases
    WHERE name = 'Project1Todo')
    DROP DATABASE Project1Todo
GO
CREATE DATABASE [Project1Todo]
 CONTAINMENT = NONE
GO
ALTER DATABASE [Project1Todo] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Project1Todo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Project1Todo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Project1Todo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Project1Todo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Project1Todo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Project1Todo] SET ARITHABORT OFF 
GO
ALTER DATABASE [Project1Todo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Project1Todo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Project1Todo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Project1Todo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Project1Todo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Project1Todo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Project1Todo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Project1Todo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Project1Todo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Project1Todo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Project1Todo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Project1Todo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Project1Todo] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Project1Todo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Project1Todo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Project1Todo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Project1Todo] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Project1Todo] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Project1Todo] SET  MULTI_USER 
GO
ALTER DATABASE [Project1Todo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Project1Todo] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Project1Todo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Project1Todo] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Project1Todo] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Project1Todo]
GO
/****** Object:  Table [dbo].[Category]    Script Date: 1/21/2017 10:15:23 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[catID] [int] IDENTITY(1,1) NOT NULL,
	[catName] [nvarchar](max) NOT NULL,
	[dateCompleted] [datetime] NULL,
	[deleted] [int] NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[catID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Item]    Script Date: 1/21/2017 10:15:23 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Item](
	[itemID] [int] NOT NULL,
	[itemName] [nvarchar](max) NOT NULL,
	[listID] [int] NOT NULL,
	[dateCreated] [datetime] NULL,
	[dateCompleted] [datetime] NULL,
	[completed] [int] NULL,
 CONSTRAINT [PK_Item] PRIMARY KEY CLUSTERED 
(
	[itemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[List]    Script Date: 1/21/2017 10:15:23 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[List](
	[listID] [int] IDENTITY(1,1) NOT NULL,
	[listName] [nvarchar](max) NOT NULL,
	[dateCreated] [datetime] NULL,
 CONSTRAINT [PK_List] PRIMARY KEY CLUSTERED 
(
	[listID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ListCategoryJunction]    Script Date: 1/21/2017 10:15:23 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ListCategoryJunction](
	[listID] [int] NOT NULL,
	[catID] [int] NOT NULL,
 CONSTRAINT [PK_ListCategoryJunction] PRIMARY KEY CLUSTERED 
(
	[listID] ASC,
	[catID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Item]  WITH CHECK ADD  CONSTRAINT [FK_Item_List] FOREIGN KEY([listID])
REFERENCES [dbo].[List] ([listID])
GO
ALTER TABLE [dbo].[Item] CHECK CONSTRAINT [FK_Item_List]
GO
ALTER TABLE [dbo].[ListCategoryJunction]  WITH CHECK ADD  CONSTRAINT [FK_ListCategoryJunction_Category] FOREIGN KEY([catID])
REFERENCES [dbo].[Category] ([catID])
GO
ALTER TABLE [dbo].[ListCategoryJunction] CHECK CONSTRAINT [FK_ListCategoryJunction_Category]
GO
ALTER TABLE [dbo].[ListCategoryJunction]  WITH CHECK ADD  CONSTRAINT [FK_ListCategoryJunction_List] FOREIGN KEY([listID])
REFERENCES [dbo].[List] ([listID])
GO
ALTER TABLE [dbo].[ListCategoryJunction] CHECK CONSTRAINT [FK_ListCategoryJunction_List]
GO
USE [master]
GO
ALTER DATABASE [Project1Todo] SET  READ_WRITE 
GO