USE [master]
GO

/****** Object:  Database [Project1Todo]    Script Date: 1/25/2017 6:16:39 PM ******/
CREATE DATABASE [Project1Todo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Project1Todo', FILENAME = N'D:\Programs\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Project1Todo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Project1Todo_log', FILENAME = N'D:\Programs\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\Project1Todo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Project1Todo] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Project1Todo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Project1Todo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Project1Todo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Project1Todo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Project1Todo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Project1Todo] SET ARITHABORT OFF 
GO

ALTER DATABASE [Project1Todo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Project1Todo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Project1Todo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Project1Todo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Project1Todo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Project1Todo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Project1Todo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Project1Todo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Project1Todo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Project1Todo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Project1Todo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Project1Todo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Project1Todo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Project1Todo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Project1Todo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Project1Todo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Project1Todo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Project1Todo] SET RECOVERY FULL 
GO

ALTER DATABASE [Project1Todo] SET  MULTI_USER 
GO

ALTER DATABASE [Project1Todo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Project1Todo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Project1Todo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Project1Todo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Project1Todo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Project1Todo] SET QUERY_STORE = OFF
GO

USE [Project1Todo]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Project1Todo] SET  READ_WRITE 
GO

